chat/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('testing/', views.index, name='index'),
    path('<str:room_name>/', views.chatbox, name='chat'),
    path('create/thread/', views.create_chat, name='create-thread'),
    path('save/chat/', views.save_chat, name='save-chat'),
    path('load/chat/', views.load_chat),
    path('read/done/', views.is_read_chat),
    path('load/read/', views.load_read)
]

core/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

# from core.settings import MEDIA_ROOT

from .views import delete_user, login_view, logout_view, edit_password

from graphene_django.views import GraphQLView

urlpatterns = [
    path('', include('kepesertaan.urls')),
    path('chat/', include('chat.urls')),
    path('mychats/', include('mychats.urls')),
    path('kunjungan/', include('kunjungan.urls')),
    path('admin-page/', include('admin_page.urls')),
    path("graphql", csrf_exempt(GraphQLView.as_view(graphiql=True)), name="graphql"),
    path('accounts/login/', login_view, name='login'),
    path('accounts/logout/', logout_view, name='logout'),
    path('ganti/password/<int:pk>', edit_password, name='edit-password'),
    path('accounts/reset_password/', auth_views.PasswordResetView.as_view(template_name="registration/reset_password.html"), name="reset_password"),
    path('accounts/reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name="registration/reset_password_confirmation.html"), name="password_reset_done"),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('accounts/reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('hapus/user/<int:pk>', delete_user, name='hapus-user'),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kunjungan/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.kunjungan, name='kunjungan-list'),
    path('buat/', views.simpan_kunjungan, name='buat-kunjungan'),
    path('detil/<int:pk>/', views.detail_kunjungan, name='detil-kunjungan'),
    # path('detil/<int:pk>/', views.docPDF, name='detil-kunjungan'),
    path('approval/list/', views.daftar_approval_kunjungan, name='list-approval'),
    path('approval/<int:pk>/done/', views.approval_kunjungan, name='approval-kunjungan'),
    path('pdf/<int:pk>/', views.GeneratePDF.as_view(), name='generate-pdf'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kepesertaan/models.py
import os
from django.conf import settings
from django.db import models
# from django.contrib.auth import get_user_model
# from django.core.files.storage import FileSystemStorage
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
# from django.db.models.signals import post_save
# from django.dispatch import receiver

# User = get_user_model()

info_save = '/home/reah4319/jrealitas/public/'

NIK_VALIDATOR = RegexValidator("^\d{16}$","Format NIK Tidak Sesuai")
HP_VALIDATOR = RegexValidator("^(08+[1-9])([0-9]{7,10})$", "Format NO HP TIDAK SESUA!!!")

class Kantor(models.Model):
    kode_kantor = models.CharField(max_length=3)
    nama_kantor = models.CharField(max_length=100)
    alamat = models.CharField(max_length=250)

    def __str__(self):
        return f'{self.kode_kantor} - {self.nama_kantor}'

class Bidang(models.Model):
    kode_bidang = models.CharField(max_length=3)
    nama_bidang = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.kode_bidang} - {self.nama_bidang}'

class Jabatan(models.Model):
    bidang = models.ForeignKey(Bidang, on_delete=models.CASCADE)
    kode_jabatan = models.CharField(max_length=3)
    nama_jabatan = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.kode_jabatan} - {self.nama_jabatan}'

# @receiver(post_save, sender=User)
# def post_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(username=instance)
    
class Profile(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    nama = models.CharField(max_length=100)
    no_hp = models.CharField(max_length=13, validators=[HP_VALIDATOR])
    jabatan = models.ForeignKey(Jabatan, on_delete=models.CASCADE)
    kode_kantor = models.ForeignKey(Kantor, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.username} - {self.nama}'



class Perusahaan(models.Model):
    nama_pemilik = models.CharField(max_length=100, blank=True, null=True)
    nik = models.CharField(max_length=16, validators=[NIK_VALIDATOR], blank=True, null=True)
    jabatan = models.CharField(max_length=50, default="HRD")
    email = models.EmailField(max_length=100, blank=True, null=True)
    no_hp = models.CharField(max_length=13, validators=[HP_VALIDATOR], blank=True, null=True)
    npp = models.CharField(max_length=8)
    nama_perusahaan = models.CharField(max_length=200)
    nama_pic = models.CharField(max_length=100)
    alamat = models.CharField(max_length=250, blank=True, null=True)
    kode_pos = models.CharField(max_length=5, blank=True, null=True)
    npwp_prsh = models.CharField(max_length=15, blank=True, null=True)
    desa_kel = models.CharField(max_length=100, blank=True, null=True)
    kecamatan = models.CharField(max_length=100, blank=True, null=True)
    kota_kab = models.CharField(max_length=100, blank=True, null=True)
    status = models.BooleanField(default=False)
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    pembina = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.npp} - {self.nama_perusahaan}'

    def total_npp(*args, **kwargs):
        
        npp = Perusahaan.objects.select_related('pembina').filter(pembina__username__username=kwargs['kwargs'])
        return npp.count()


class Tenaga_kerja(models.Model):
    npp = models.ForeignKey(Perusahaan, on_delete=models.CASCADE)
    nama = models.CharField(max_length=100)
    no_kartu = models.CharField(max_length=11)
    no_hp = models.CharField(max_length=13, validators=[HP_VALIDATOR])
    email = models.EmailField(max_length=100, blank=True, null=True)
    tgl_lahir = models.DateField()
    tgl_keps = models.DateField()
    tgl_na = models.DateField(blank=True, null=True)

    def __str__(self):
        return f'{self.no_kartu} - {self.nama}'

class Informasi(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    judul = models.CharField(max_length=200)
    attachment = models.FileField(upload_to='informasi/attachment', blank=True, null=True)
    isi = models.TextField()
    created_by = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.created_by.username.username} - {self.judul}'

kunjungan/models.py
from io import BytesIO
# from msilib.schema import File
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver
from kepesertaan.models import Perusahaan, Profile

import qrcode
from PIL import Image, ImageDraw

User = get_user_model()

TUJUAN = (
    ('1','SOSIALISASI'),
    ('2','KELENGKAPAN DATA KLAIM'),
    ('3','PENYELESAIAN KASUS JKK'),
    ('4','KUNJUNGAN LAPANGAN / CEK KASUS'),
    ('5','PEMBINAAN FASILITAS KESEHATAN (PLKK)')
)

STATUS = (
    ('0','PROSES'),
    ('1','SETUJU'),
    ('2','DITOLAK')
)

class berita_kunjungan(models.Model):
    petugas = models.ForeignKey(Profile, on_delete=models.CASCADE)
    to_perusahaan = models.ForeignKey(Perusahaan, on_delete=models.CASCADE)
    to_nama = models.CharField(max_length=50)
    to_jabatan = models.CharField(max_length=50)
    to_alamat = models.CharField(max_length=500)
    to_no_hp = models.CharField(max_length=13)
    to_lokasi = models.CharField(max_length=100)
    tujuan = models.CharField(choices=TUJUAN, max_length=2)
    hasil = models.TextField()
    # qrcode_pembina = models.ImageField(upload_to='media/kunjungan/pembina/')
    # qrcode_to_nama = models.ImageField(upload_to='media/kunjungan/toNama/')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.petugas.username.username} - {self.to_perusahaan.npp} - {self.to_nama}'

    # def save(self, *args, **kwargs):
    #     qr =qrcode.QRCode(
    #         version=20,
    #         error_correction=qrcode.ERROR_CORRECT_M,
    #         box_size=50,
    #         border=2
    #     )

    #     data_pembina = """
    #     Nama : {}
    #     Kode Pembina : {}
    #     Jabatan : {}
    #     """.format(self.petugas.nama, self.petugas.username.username, self.petugas.jabatan.nama_jabatan)

    #     data_to_nama = """
    #     Nama : {}
    #     Jabatan/Sebagai : {}
    #     No Hp : {}
    #     """.format(self.to_nama, self.to_jabatan, self.to_no_hp)

    #     qr1_img = qrcode.make(data_pembina)
    #     qr2_img = qrcode.make(data_to_nama)

    #     canvas1 = Image.new('RGB', (300,300), 'white')
    #     draw1 = ImageDraw.Draw(canvas1)
    #     canvas1.paste(qr1_img)
    #     fname1 = f'{self.petugas.username.username}-{self.created}.PNG'
    #     buff1 = BytesIO()
    #     canvas1.save(buff1, 'PNG')
    #     self.qrcode_pembina.save(fname1, File(buff1), save=False)
    #     canvas1.close()

    #     canvas2 = Image.new('RGB',(300,300), 'white')
    #     draw2 = ImageDraw.Draw(canvas2)
    #     canvas2.paste(qr2_img)
    #     fname2 = f'{self.to_nama}-{self.created}.PNG'
    #     canvas2.save(buff1, 'PNG')
    #     self.qrcode_to_nama.save(fname2, File(buff1), save=False)
    #     canvas2.close()

        # return super().save(*args, **kwargs)

class approval_bak(models.Model):
    berita_acara = models.ForeignKey(berita_kunjungan, on_delete=models.CASCADE)
    # approved = models.BooleanField(default=False)
    status = models.CharField(max_length=1, choices=STATUS, default='0')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.berita_acara.to_perusahaan.nama_perusahaan}'

@receiver(post_save, sender=berita_kunjungan, dispatch_uid="create_approval")
def kirim_approval(sender, instance, created, **kwargs):
    if created:
        approval_bak.objects.create(berita_acara=instance)

kunjungan/templates/kunjungan/approval.html
{% extends 'base.html' %}

{% block title %}APPROVAL BERITA ACARA{% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    APPROVAL BERITA ACARA <b>{{request.user}}</b>
                </div>
                <div class="card-body">
                    {% if datas %}
                    <div class="table table-responsive mt-2">
                        <div class="row">
                            <div class="col-sm-12">
                                
                                <table id="approval_kunjungan" class="table table-bordered">
                                    <thead>
                                        <tr class="text-center">
                                            <th>#</th>
                                            <th>JUDUL</th>
                                            <th>PETUGAS</th>
                                            <th>TANGGAL </br>KUNJUNGAN</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for data in datas %}
                                            <tr>
                                                <td class="text-center">{{forloop.counter}}</td>
                                                <td class="text-center">{{data.berita_acara.get_tujuan_display}}</td>
                                                <td class="text-center">{{data.berita_acara.petugas.nama}}</td>
                                                <td class="text-center">{{data.berita_acara.created|date:"D, d-m-Y"}}</td>
                                                <td>
                                                {% if data.status == '1' %}
                                                    <button type="button" class="btn btn-sm btn-success" disabled>SETUJU</button>
                                                {% elif data.status == '2' %}
                                                    <button type="button" class="btn btn-sm btn-danger" disabled>TOLAK</button>
                                                {% else %}
                                                    <a href="#" class="btn btn-sm btn-warning" id="approval_bak" data-pk={{data.pk}}>PROSES</a>
                                                {% endif %}
                                                    <a href="{% url 'detil-kunjungan' pk=data.berita_acara.pk %}" class="btn btn-sm btn-primary float-right" target="_blank">Detail</a>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                {% else %}
                                <p class="text-md-center" style="font-weight:600;">Tidak ada Berita Acara</p>
                                {% endif %}
                               
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascripts %}
<script>
    const pk = $('#approval_bak').attr('data-pk')
    $('#approval_bak').on('click', function () {
        const swalWithBootstrapButtons = Swal.mixin({
            customClass: {
              confirmButton: 'btn btn-success btn-sm',
              cancelButton: 'btn btn-danger btn-sm'
            },
            buttonsStyling: true
          })
        swalWithBootstrapButtons.fire({
            title: 'Anda Yakin ?',
            text: "Proses Ini tidak bisa dibatalkan!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Ya, Setuju!',
            cancelButtonText: 'Tidak, Tolak!',
            reverseButtons: true
          }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    method:"POST",
                    url:`/kunjungan/approval/${pk}/done/`,
                    data:{
                        'status':'1'
                    },
                    success:function(data){
                        swalWithBootstrapButtons.fire(
                            'Approved!',
                            'Berita Acara Kunjungan Sudah Anda Setujui',
                            'success'
                        )
                        location.reload();
                    },
                    error:function(err){
                        console.log(err)
                    }
                })
              
            } else if (
              /* Read more about handling dismissals below */
              result.isDismissed
            ) {
              $.ajax({
                  method:"POST",
                  url:`/kunjungan/approval/${pk}/done/`,
                  data:{
                      'status':'2'
                  },
                  success:function(data){
                      swalWithBootstrapButtons.fire(
                          'Tolak',
                          'Berita Acara Kunjungan di Tolak',
                          'error'
                      )
                      location.reload();
                  },
                  error:function(err){
                      console.log(err)
                  }
              })
              
          }
        })
    })
</script>
{% endblock javascripts %}

kunjungan/templates/kunjungan/buat_kunjungan.html
<h1>Buat Kunjungan</h1>

kunjungan/templates/kunjungan/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}BAK{% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card mb-3">
                <div class="card-header">
                    <div class="nav-tabs-navigation">
                        <div class="nav-tabs-wrapper">
                            <ul class="nav nav-tabs" data-tabs="tabs">
                                <li class="nav-item mr-2">
                                    <a href="#id_list_kunjungan" class="color-nav-link nav-link active" data-toggle="tab">
                                        <i class="fas fa-fw fa-users"> </i> List Kunjungan  
                                    </a>
                                </li>
                                <li class="nav-item mr-2">
                                    <a href="#id_buat_kunjungan" class="color-nav-link nav-link" data-toggle="tab">
                                        <i class="fas fa-fw fa-user-plus"> </i>Buat Kunjungan
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="tab-content">
                        <div class="tab-pane active" id="id_list_kunjungan">
                            <div class="table-responsive mt-3">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <table id="kunjungan_id" class="table table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th>Petugas</th>
                                                    <th>Tujuan</th>
                                                    <th>alamat</th>
                                                    <th>Tanggal</th>
                                                    <th>Action</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for data in datas %}
                                                    <tr>
                                                        <td>{{forloop.counter}}</td>
                                                        <td>{{data.petugas.username.username}}</td>
                                                        <td>{{data.to_perusahaan.npp}} - {{data.get_tujuan_display}}</td>
                                                        <td>{{data.to_alamat}}</td>
                                                        <td>{{data.created|date:"D, d-m-Y"}}</td>
                                                        <td>
                                                            {% if data.status == '1' %}
                                                                <button type="button" class="btn btn-sm btn-success" disabled>SETUJU</button>
                                                            {% elif data.status == '2' %}
                                                                <button type="button" class="btn btn-sm btn-danger" disabled>TOLAK</button>
                                                            {% else %}
                                                                <a href="#" class="btn btn-sm btn-warning" disabled>PROSES</a>
                                                            {% endif %}             
                                                            <br />                                               
                                                            <a href="{% url 'detil-kunjungan' pk=data.pk %}" class="btn btn-sm btn-primary mt-2" target="_blank">Detail</a>
                                                        </td>
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane" id="id_buat_kunjungan">
                            
                            <h6 class="text-center font-weight-bold">BERITA ACARA KUNJUNGAN</h6>
                            <hr>
                            <form action="POST" id="kunjungan_form">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col col-md-6">
                                        <div class="form-group">
                                            <label for="id_tujuan">TUJUAN</label>
                                            <span style="color:red;">*</span>
                                            {{form.tujuan}}
                                        </div>
                                        <div class="form-group">
                                            <label for="id_to_nama">NAMA</label>
                                            <span style="color:red;">*</span>
                                            {{form.to_nama}}
                                        </div>
                                        <div class="form-group">
                                            <label for="id_to_jabatan">JABATAN</label>
                                            <span style="color:red;">*</span>
                                            {{form.to_jabatan}}
                                        </div>
                                        <div class="form-group">
                                            <label for="id_to_jabatan">LOKASI</label>
                                            <span style="color:red;">*</span>
                                            {{form.to_lokasi}}
                                        </div>
                                    </div>
                                    <div class="col col-md-6">
                                        <div class="form-group">
                                            <label for="id_to_alamat">ALAMAT</label>
                                            <span style="color:red;">*</span>
                                            {{form.to_alamat}}
                                        </div>
                                        <div class="form-group">
                                            <label for="id_to_no_hp">NO HANDPHONE</label>
                                            <span style="color:red;">*</span>
                                            {{form.to_no_hp}}
                                        </div>
                                        <div class="form-group">
                                            <label for="id_petugas">PETUGAS</label>
                                            <span style="color:red;">*</span>
                                            <input type="text" name="petugas" id="id_petugas" class="form-control" value="{{request.user}}" disabled>
                                        </div>
                                        <div class="form-group">
                                            <label for="id_npp">KODE PERUSAHAAN</label>
                                            <span style="color:red;">*</span>
                                            <select class="form-control" id="id_npp" name="npp">
                                                <option value="0">.....</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="form-group">
                                            <label for="id_hasil">HASIL KUNJUNGAN</label>
                                            {{form.hasil}}
                                        </div>
                                    </div>
                                </div>
                                <button id="id_buat" class="btn btn-primary float-right" type="button">Simpan</button>
                            </form>
                            <div
                            class="modal fade"
                            id="exampleModal"
                            tabindex="-1"
                            role="dialog"
                            aria-labelledby="exampleModalLabel"
                            aria-hidden="true"
                            >
                            <div class="modal-dialog">
                                <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">SUCCESS</h5>
                                    <button
                                    type="button"
                                    class="close"
                                    data-dismiss="modal"
                                    aria-label="Close"
                                    >
                                    <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    ...
                                </div>
                                <div class="modal-footer">
                                    <button
                                    type="button"
                                    class="btn btn-secondary"
                                    data-dismiss="modal"
                                    >
                                    Close
                                    </button>
                                   
                                </div>
                                </div>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascripts %}
<script src="{% static 'kunjungan/js/kunjungan.js' %}"></script>
{% endblock javascripts %}