chat/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('testing/', views.index, name='index'),
    path('<str:room_name>/', views.chatbox, name='chat'),
    path('create/thread/', views.create_chat, name='create-thread'),
    path('save/chat/', views.save_chat, name='save-chat'),
    path('load/chat/', views.load_chat),
    path('read/done/', views.is_read_chat),
    path('load/read/', views.load_read)
]

core/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

# from core.settings import MEDIA_ROOT

from .views import delete_user, login_view, logout_view, edit_password

from graphene_django.views import GraphQLView

urlpatterns = [
    path('', include('kepesertaan.urls')),
    path('chat/', include('chat.urls')),
    path('mychats/', include('mychats.urls')),
    path('kunjungan/', include('kunjungan.urls')),
    path('admin-page/', include('admin_page.urls')),
    path("graphql", csrf_exempt(GraphQLView.as_view(graphiql=True)), name="graphql"),
    path('accounts/login/', login_view, name='login'),
    path('accounts/logout/', logout_view, name='logout'),
    path('ganti/password/<int:pk>', edit_password, name='edit-password'),
    path('accounts/reset_password/', auth_views.PasswordResetView.as_view(template_name="registration/reset_password.html"), name="reset_password"),
    path('accounts/reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name="registration/reset_password_confirmation.html"), name="password_reset_done"),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('accounts/reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('hapus/user/<int:pk>', delete_user, name='hapus-user'),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.aggregates import Max

#model testing channel
from django.conf import settings
from django.db.models import Q


class ThreadChat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user1')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user2')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.pk}'

class Message(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='from_user')
    # recipent = models.ForeignKey(User, on_delete=models.CASCADE, related_name='to_user')
    body = models.TextField(max_length=1000, blank=True, null=True)
    thread = models.ForeignKey(ThreadChat, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def send_message(from_user, body):
        sender_message = Message(
            # user=from_user,
            sender=from_user,
            # recipent=to_user,
            body=body,
            is_read=False
        )
        sender_message.save()

        # recipent_message = Message(
        #     user=to_user,
        #     sender=from_user,
        #     body=body,
        #     recipent=from_user,
        # )
        # recipent_message.save()

        return sender_message

    def get_messages(user):
        users = []
        messages = Message.objects.filter(user=user).values('recipent').annotate(last=Max('date')).order_by('-last')
        for message in messages:
            users.append({
                'user': User.objects.get(pk=message['recipent']),
                'last': message['last'],
                'unread': Message.objects.filter(user=user, recipent__pk=message['recipent'], is_read=False)
            })

        return users



class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username):
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) | Q(second__username=other_username)
        qlookup2 = Q(firs__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                    first=user,
                    second=user2
                )
                obj.save()
                return obj, True
            return None, False

class Thread(models.Model):
    first = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    # def broadcast(self, msg=None):
    #     if msg is not None:
    #         broadcast_msg_to_chat(msg, group_name=self.room_group_name, )

class ChatMessage(models.Model):
    thread = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

chat/views.py
from django.db.models import Q
from django.core import serializers
from django.http.response import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from .models import Message, ThreadChat

from kepesertaan.models import Perusahaan, Profile


#testing channels
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from django.http import Http404, HttpResponseForbidden
from django.views.generic.edit import FormMixin

from .forms import ComposeForm
from .models import Thread, ChatMessage


@login_required
def index(request):
    users_jab = Profile.objects.select_related('username').filter(username__username=request.user)
    
    if users_jab.exists() :
        users = Profile.objects.exclude(username__username=request.user)
        hrd = Perusahaan.objects.all()
    else:
        users = Profile.objects.exclude(jabatan__kode_jabatan='70')
        
        hrd = Perusahaan.objects.none()

    context = {
        'users_jab':users_jab,
        'users':users,
        'hrds':hrd
    }
    return render(request, 'chat/messages.html',context)

@login_required
def inbox(request):
    pesan = Message.objects.filter(is_read=False).all()
    users_jab = Profile.objects.select_related('username').filter(username__username=request.user)
    if users_jab.exists() :
        users = Profile.objects.exclude(username__username=request.user)
        hrd = Perusahaan.objects.all()

    else:
        users = Profile.objects.exclude(jabatan__kode_jabatan='70')
        # hrd = Perusahaan.objects.select_related('username','pembina').filter(pembina__username__username=request.user)
        hrd = Perusahaan.objects.none()

    context = {
        'users_jab':users_jab,
        'users':users,
        'hrds':hrd,
        'chats':pesan,
    }
    
    return render(request, 'chat/direct.html',context)
   
def chatbox(request, username):
    pass

@login_required
@csrf_exempt
def load_chat(request):
    user = request.user.pk
    # to_user = request.POST.get('to_user')
    thread_id = request.POST.get('thread_id')
    # to_user_pk = User.objects.get(username=to_user)
    # threads = ThreadChat.objects.filter(Q(user_id=user)|Q(to_user_id=user),Q(user_id=to_user)|Q(to_user_id=to_user))
    threads = ThreadChat.objects.filter(pk=int(thread_id))

    if threads.exists():
        # messages = Message.objects.filter(thread_id=threads[0].id).update(is_read=True)
        testing = Message.objects.filter(thread_id=thread_id).values('pk','sender__pk','sender__username','body','date','is_read').order_by('date')
        
        # data = []
        # for message in messages:
        #     user = message.user
            
    # if messages.exists():
        # list_messages = serializers.serialize('json',testing)
        
        return JsonResponse({'data':list(testing)}, safe=False)
    else:
        return JsonResponse({})

@csrf_exempt
def create_chat(request):
    from_user = request.user.pk

    to_user = request.POST.get('to_user')
    # to_user_pk = User.objects.get(username=to_user)
    cek_id = ThreadChat.objects.select_related('user','to_user').filter(Q(user_id=from_user) | Q(user_id=to_user), Q(to_user_id=to_user) | Q(to_user_id=from_user))
    # threads = serializers.serialize('json', cek_id)
    if cek_id.exists():
        threads = cek_id.values('pk','user__pk','user__username','to_user__pk','to_user__username')
        return JsonResponse({'data':list(threads)}, safe=False)
    else:
        threads = ThreadChat.objects.create(user_id=from_user, to_user_id=to_user)

        return JsonResponse({'success':'Save!'})

@csrf_exempt
def is_read_chat(request):
    from_user = request.user.pk
    # thread_id = request.POST.get('user')
    # print(thread_id)
    to_user = request.POST.get('user')
    # threads = ThreadChat.objects.filter(pk=int(thread_id))
    threads = ThreadChat.objects.filter(Q(user_id=from_user) | Q(user_id=to_user), Q(to_user_id=to_user) | Q(to_user_id=from_user))
    try:
        if threads.exists():
            # messages = Message.objects.filter(thread_id=threads[0].id).update(is_read=True)
            messages = Message.objects.filter(thread_id=threads[0]).update(is_read=True)
            
            return JsonResponse({'data':'Done'})
    except ThreadChat.DoesNotExist:
        return JsonResponse({'error':'Data Tidak ditemukan!'})


@csrf_exempt
def load_read(request):
    from_user = request.user.pk
    to_user = request.POST.get('to_user')
    # print(to_user)
    threads = ThreadChat.objects.filter(Q(user_id=from_user) | Q(user_id=to_user), Q(to_user_id=to_user) | Q(to_user_id=from_user))
    try:
        if threads.exists():
            pesan = Message.objects.filter(thread_id=threads[0].id).filter(is_read=False).values('sender_id','is_read','thread__user','thread__to_user')
            # pesan = serializers.serialize('json', [pesan])
            return JsonResponse({'data':list(pesan)}, safe=False)
    except ThreadChat.DoesNotExist:
        return JsonResponse({'error':'Data Not Found!'})

@csrf_exempt
def save_chat(request):
    user = request.user.pk
    thread_id = request.POST.get('thread_id')
    # to_user = request.POST.get('to_user')
    body = request.POST.get('pesan')
    # to_user_pk = User.objects.get(username=to_user)
    cek_id = ThreadChat.objects.filter(pk=int(thread_id))
    
    if cek_id.exists():  
        _ = Message.objects.create(thread_id=int(thread_id), sender_id=user, body=body)
        last_pesan = Message.objects.filter(thread_id=int(thread_id)).order_by('-date')[0]
        pesan = serializers.serialize('json', [last_pesan])

        return JsonResponse({'data':pesan})


class InboxView(LoginRequiredMixin, ListView):
    template_name = 'chat/inbox.html'
    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = './'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username = self.kwargs.get("username")
        obj, created = Thread.objects.get_or_new(self. request.user, other_username)
        if obj == None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

chat/templates/chat/dialogs.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Chat{% endblock title %}

{% block stylesheets %}

{% endblock stylesheets %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col col-4">
            <div class="card">
                <div class="card-body">
                    <div id="id_from_user" style="overflow-y: scroll; height:350px;">
                        {% if users_jab %}
                        {% for hrd in hrds %}
                        <ul class="list-group">
                            <a class="list-group-item nav-link text-grey mb-2" href="javascript:void(0)" id="to_user" data-user="{{hrd.username.pk}}">{{hrd.username.username}}</a>
                            
                        </ul>
                        {% endfor %}
                        {% else %}
                        {% for user in users %}
                        <ul class="list-group">
                            <a class="list-group-item nav-link text-grey mb-2" href="javascript:void(0)" id="to_user" data-user={{user.username.pk}}>{{user.username}}</a>
                        </ul>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col col-8">
            <div class="card">
                <div class="col" id="pesan">
                    <p class="mt-2" id="sender" data="{{request.user.id}}">{{request.user}}</p>
                    
                    <hr />
                </div>
                <div class="col col-xl-12">
                    <div id="id_pesan" style="overflow-y: scroll; height:350px;"></div>
                </div>
                <div class="col">
                    <div id="id_footer">
                        <div class="row">
                             <div class="col-md-10">
                                 <div class="form-group">   
                                     <div contenteditable class="form-control" id="pesan_id"></div>
                                 </div>
                             </div>
                             <div class="col-md-2">
                                 <div class="form-group">
                                     <button type="button" class="btn btn-primary" id="kirim_pesan">Kirim</button>
                                 </div>
                             </div>
                        </div>
                     </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block javascripts %}
<script src="{% static 'chat/chats.js' %}"></script>
{% endblock javascripts %}

chat/templates/chat/direct.html
{% extends 'base.html' %}
{% load static %}

{% block title %}RealChat{% endblock title %}

{% block stylesheets %}
<style>
.cfooter{
    box-sizing: border-box;
    border-bottom:1px solid #eee;

}

.time {
  display: block;
  font-size: 0.8rem;
  background: white;
  /* padding: 0.25rem 1rem; */
  border-radius: 2rem;
  /* color: #999; */
  width: fit-content;
  /* margin: 0 auto; */
  /* margin: 8px 0 0; */
}

.time.sender {
  display: block;
  margin: 0 0 0 auto;
  font-size: 0.8rem;
  background: white;
  border-radius: 2rem;
  /* color: #999; */
  
}

.message {
  box-sizing: border-box;
  padding: 0.5rem 1rem;
  margin: 0 0 2px 0;
  background: #ccc;
  color:black;
  border-radius: 1.125rem 1.125rem 1.125rem 0;
  min-height: 2.25rem;
  width: fit-content;
  max-width: 66%;

  box-shadow: 0 0 2rem rgba(black, 0.075),
      0rem 1rem 1rem -1rem rgba(black, 0.1);
}
.message.sender {
  margin: 0 0 0 auto;
  border-radius: 1.125rem 1.125rem 0 1.125rem;
  background: #333;
  color: white;
}

#to_user:hover{
    background-color: black;
}

.new_message {
    animation: example 1.5s infinite;
}

@keyframes example {
    0% {
        background-color: grey;
    }
    50% {
        background-color: greenyellow;
    }

    100%{
        background-color: white;
    }
}
</style>
{% endblock stylesheets %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col col-4">
            <div class="card">
                <div class="card-body">
                    <div id="id_from_user" style="overflow-y: scroll; height:430px;">
                        {% include 'chat/users.html' %}
                        
                    </div>
                </div>
            </div>
        </div>
        <div class="col col-8">
            <div class="card">
                <div class="col" id="pesan">
                    <p class="mt-2" id="sender" data="{{request.user.id}}" hidden>{{request.user}}</p>
                    
                    <hr />
                </div>
                <div class="col col-xl-12 cfooter">
                    <div id="id_pesan" style="overflow-y: scroll; height:350px;">
                    </div>
                </div>
                <div class="col mt-2">
                    <div id="id_footer">
                        <div class="row">
                             <div class="col-md-10">
                                 <div class="form-group">   
                                     <div contenteditable class="form-control" id="pesan_id">

                                     </div>
                                 </div>
                             </div>
                             <div class="col-md-2">
                                 <div class="form-group">
                                     <button type="button" class="btn btn-primary" id="kirim_pesan">Kirim</button>
                                 </div>
                             </div>
                        </div>
                     </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block javascripts %}
<script src="{% static 'chat/reconnecting-websocket.js' %}"></script>
<script>
    var i = window.location.href
    var protocol = window.location.protocol
    var host = window.location.host
    if(protocol === 'https'){
        proWs = 'wss'
    }else{
        proWs = 'ws'
    }
    console.log(i)
    // var endpoint = 'ws://127.0.0.1:8000/chat/status/'
    var endpoint = proWs+'://'+host+'/chat/status/'


    var socket = new ReconnectingWebSocket(endpoint)

    socket.onopen = function(e) {
        // console.log ("open", e);
       
    }

    var ul = $("ul#to_users").length + 1
    //console.log(ul)

    socket.onmessage = function(e) {
        
        // var from_sender = $("#sender").text()
        
        // var userData = JSON.parse(e.data)
        
        // datas = JSON.parse(userData.chat_users)
        
        // datas.map(data => {
            
        //     if(data.sender__username !== from_sender){
        //         $("#to_user").addClass("new_message")
        //     }
        // })
        
    }
    socket.onerror = function(e) {
        console.log ("error", e)
    }
    socket.onclose = function(e) {
        console.log ("close", e)
    }

    
</script>

<script src="{% static 'chat/chats.js' %}"></script>
{% endblock javascripts %}

chat/templates/chat/index.html
<h1>Ini Index Chat Room<h1>

chat/templates/chat/messages.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Testing Chat box
{% endblock title %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'chat/messages.css' %}">
<script src="https://kit.fontawesome.com/54550ccbba.js" crossorigin="anonymous"></script>
{% endblock stylesheets %}

{% block content %}
<div class="container mychat" id="mychat">
    <div class="row center">
        <div class="contacts">
            <i class="fas fa-bars fa-2x"></i>
            <h2>Contacts</h2>
            {% if users_jab %}
            {% for hrd in hrds %}
            <div class="contact" href="javascript:void(0)" id="to_user" data-user="{{hrd.username.pk}}">
                <div class="pic rogers"></div>
                <div class="badge">14</div>
                <div class="name">{{hrd.username.username}}</div>
                <div class="message">That is America's ass 🇺🇸🍑</div>
            </div>
            {% endfor %}
            {% else %}
            {% for user in users %}
            <div class="contact" href="javascript:void(0)" id="to_user" data-user="{{user.username.pk}}">
                <div class="pic rogers"></div>
                <div class="badge">14</div>
                <div class="name">{{user.username}}</div>
                <div class="message">That is America's ass 🇺🇸🍑</div>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <div class="chat">
            <div class="contact bar" id="chat-bar">
                <div class="pic stark"></div>
                <div id="sender" data="{{request.user.id}}" data-username="{{request.user}}" hidden></div>
                
            </div>
            <div class="pesan">
                <div id="chat" class="messages">
               
                </div>
            </div>
            <div class="input">
                <i class="fas fa-camera"></i>
                <i class="far fa-laugh-beam"></i>
                <input type="text" name="" id="pesan_id" placeholder="Type your message here!">
                <button type="button" class="btn btn-sm btn-success" id="kirim_pesan"><i class="fa-solid fa-paper-plane"></i></button>
            </div>
        </div>  
    </div>
</div>

{% endblock content %}

{% block javascripts %}
<script src="{% static 'chat/messages.js' %}"></script>
{% endblock javascripts %}

chat/templates/chat/thread.html
{% extends 'base.html' %}

{% block title %}JrealChat{% endblock title %}

{% block content %}
<h3>Thread for {% if user != object.first %} {{object.first}} {% else %} {{object.second}} {% endif %}</h3>
<ul id="chat-items">
    {% for chat in object.chatmessage_set.all %}
    <li>{{chat.message}} via {{chat.user}}</li>
    {% endfor %}
</ul>

<form id="form" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Send" class="btn btn-primary">

</form>
{% endblock content %}

{% block javascripts %}
<script>
    var loc = window.location
    var wsStart = 'ws://'
    if(loc.protocl == 'https:'){
        wsStart = 'wss://'
    }

    var endpoint = wsStart + loc.host + loc.pathname
        
    var socket = new Webscoket(endpoint)

    socket.onmessage = function(e){
        console.log("message",e)
    }
    socket.onopen = function(e){
        console.log("open",e)
    }
    socket.onerror = function(e){
        console.log("error", e)
    }
    socket.onclose = function(e){
        console.log("closed",e)
    }
</script>
{% endblock javascripts %}

chat/templates/chat/users.html
{% if users_jab %}
{% for hrd in hrds %}
<ul class="list-group" id="to_users">
    <a class="list-group-item nav-link text-grey mb-2 mx-2" href="javascript:void(0)" id="to_user" data-user="{{hrd.username.pk}}">{{hrd.username.username}}</a>
</ul>
{% endfor %}
{% else %}
{% for user in users %}
<ul class="list-group" id="to_users">
    <a class="list-group-item nav-link text-grey mb-2" href="javascript:void(0)" id="to_user" data-user="{{user.username.pk}}">{{user.username}}</a>
</ul>
{% endfor %}
{% endif %}