chat/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('testing/', views.index, name='index'),
    path('<str:room_name>/', views.chatbox, name='chat'),
    path('create/thread/', views.create_chat, name='create-thread'),
    path('save/chat/', views.save_chat, name='save-chat'),
    path('load/chat/', views.load_chat),
    path('read/done/', views.is_read_chat),
    path('load/read/', views.load_read)
]

core/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

# from core.settings import MEDIA_ROOT

from .views import delete_user, login_view, logout_view, edit_password

from graphene_django.views import GraphQLView

urlpatterns = [
    path('', include('kepesertaan.urls')),
    path('chat/', include('chat.urls')),
    path('mychats/', include('mychats.urls')),
    path('kunjungan/', include('kunjungan.urls')),
    path('admin-page/', include('admin_page.urls')),
    path("graphql", csrf_exempt(GraphQLView.as_view(graphiql=True)), name="graphql"),
    path('accounts/login/', login_view, name='login'),
    path('accounts/logout/', logout_view, name='logout'),
    path('ganti/password/<int:pk>', edit_password, name='edit-password'),
    path('accounts/reset_password/', auth_views.PasswordResetView.as_view(template_name="registration/reset_password.html"), name="reset_password"),
    path('accounts/reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name="registration/reset_password_confirmation.html"), name="password_reset_done"),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('accounts/reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('hapus/user/<int:pk>', delete_user, name='hapus-user'),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kepesertaan/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import (index, data_user, Daftar_Perusahaan, save_to_models, download_excel,
    informasi, Daftar_Pembina, buat_info, create_info_user, page_tk, list_tk_npp, download_tk_excel,
    save_tk_to_models, edit_profile,update_binaan, edit_profile_perusahaan, pindah_binaan, Buat_Pembina,
    hapus_tk)

urlpatterns = [
    path('', index, name='dashboard'),
    path('user/data/', data_user, name='user_data'),
    path('edit/user/<int:pk>/', edit_profile, name='edit-profile'),
    path('create/npp/', Daftar_Perusahaan, name='daftar-npp'),
    path('update/perusahaan/', edit_profile_perusahaan, name='edit-npp'),
    path('buat/pembina/', Buat_Pembina, name='buat-pembina'),
    path('create/pembina/', Daftar_Pembina, name='daftar-pembina'),
    path('update/binaan/', update_binaan, name='update-binaan'),
    path('pindah/binaan/', pindah_binaan, name='pindah-binaan'),
    path('templates/upload/', save_to_models, name='upload-npp'),
    path('templates/download/', download_excel, name='download-npp'),
    path('templates/tk/download/', download_tk_excel, name='download-tk-excel'),
    path('templates/tk/upload/', save_tk_to_models, name='upload-tk'),
    path('hapus/tk/', hapus_tk, name='hapus-tk'),
    path('page/perusahaan/', page_tk, name='page-tk'),
    path('informasi/<str:npp>/list/tk/', list_tk_npp, name='list-tk'),
    path('informasi/create', buat_info, name='buat-info'),
    path('informasi/create/user/ajax', create_info_user, name='create-info-user'),
    path('informasi/', informasi, name='informasi'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kepesertaan/models.py
import os
from django.conf import settings
from django.db import models
# from django.contrib.auth import get_user_model
# from django.core.files.storage import FileSystemStorage
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
# from django.db.models.signals import post_save
# from django.dispatch import receiver

# User = get_user_model()

info_save = '/home/reah4319/jrealitas/public/'

NIK_VALIDATOR = RegexValidator("^\d{16}$","Format NIK Tidak Sesuai")
HP_VALIDATOR = RegexValidator("^(08+[1-9])([0-9]{7,10})$", "Format NO HP TIDAK SESUA!!!")

class Kantor(models.Model):
    kode_kantor = models.CharField(max_length=3)
    nama_kantor = models.CharField(max_length=100)
    alamat = models.CharField(max_length=250)

    def __str__(self):
        return f'{self.kode_kantor} - {self.nama_kantor}'

class Bidang(models.Model):
    kode_bidang = models.CharField(max_length=3)
    nama_bidang = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.kode_bidang} - {self.nama_bidang}'

class Jabatan(models.Model):
    bidang = models.ForeignKey(Bidang, on_delete=models.CASCADE)
    kode_jabatan = models.CharField(max_length=3)
    nama_jabatan = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.kode_jabatan} - {self.nama_jabatan}'

# @receiver(post_save, sender=User)
# def post_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(username=instance)
    
class Profile(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    nama = models.CharField(max_length=100)
    no_hp = models.CharField(max_length=13, validators=[HP_VALIDATOR])
    jabatan = models.ForeignKey(Jabatan, on_delete=models.CASCADE)
    kode_kantor = models.ForeignKey(Kantor, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.username} - {self.nama}'



class Perusahaan(models.Model):
    nama_pemilik = models.CharField(max_length=100, blank=True, null=True)
    nik = models.CharField(max_length=16, validators=[NIK_VALIDATOR], blank=True, null=True)
    jabatan = models.CharField(max_length=50, default="HRD")
    email = models.EmailField(max_length=100, blank=True, null=True)
    no_hp = models.CharField(max_length=13, validators=[HP_VALIDATOR], blank=True, null=True)
    npp = models.CharField(max_length=8)
    nama_perusahaan = models.CharField(max_length=200)
    nama_pic = models.CharField(max_length=100)
    alamat = models.CharField(max_length=250, blank=True, null=True)
    kode_pos = models.CharField(max_length=5, blank=True, null=True)
    npwp_prsh = models.CharField(max_length=15, blank=True, null=True)
    desa_kel = models.CharField(max_length=100, blank=True, null=True)
    kecamatan = models.CharField(max_length=100, blank=True, null=True)
    kota_kab = models.CharField(max_length=100, blank=True, null=True)
    status = models.BooleanField(default=False)
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    pembina = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.npp} - {self.nama_perusahaan}'

    def total_npp(*args, **kwargs):
        
        npp = Perusahaan.objects.select_related('pembina').filter(pembina__username__username=kwargs['kwargs'])
        return npp.count()


class Tenaga_kerja(models.Model):
    npp = models.ForeignKey(Perusahaan, on_delete=models.CASCADE)
    nama = models.CharField(max_length=100)
    no_kartu = models.CharField(max_length=11)
    no_hp = models.CharField(max_length=13, validators=[HP_VALIDATOR])
    email = models.EmailField(max_length=100, blank=True, null=True)
    tgl_lahir = models.DateField()
    tgl_keps = models.DateField()
    tgl_na = models.DateField(blank=True, null=True)

    def __str__(self):
        return f'{self.no_kartu} - {self.nama}'

class Informasi(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    judul = models.CharField(max_length=200)
    attachment = models.FileField(upload_to='informasi/attachment', blank=True, null=True)
    isi = models.TextField()
    created_by = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.created_by.username.username} - {self.judul}'

kepesertaan/forms.py
from django import forms
from django.db.models import fields
from django.forms import widgets

from .models import Informasi, Perusahaan, Profile

class UploadForm(forms.Form):
    file = forms.FileField()

class InformasiForm(forms.ModelForm):
    class Meta:
        model = Informasi
        # fields = '__all__'
        exclude = ('user',)

        widgets = {
            'judul':forms.TextInput(attrs={
                'class':'form-control','maxlength':'100'
            }),
            'isi':forms.Textarea(attrs={
                'class':'form-control', 'maxlength':'500'
            }),
            'attachment':forms.FileInput(attrs={
                'class':'from-control'
            }),
        }


class PembinaForm(forms.ModelForm):
    def __init__(self, bidang_id, *args, **kwargs):
        super(PembinaForm, self).__init__(*args, **kwargs)
        self.fields['jabatan'].queryset = self.fields['jabatan'].queryset.filter(bidang__kode_bidang=bidang_id)

    class Meta:
        model = Profile
        exclude = ('username','kode_kantor',)

        widgets = {
            'nama':forms.TextInput(attrs={
                'class':'form-control'
            }),
            'email':forms.EmailInput(attrs={
                'class':'form-control',
            }),
            'no_hp':forms.TextInput(attrs={
                'class':'form-control'
            }),
            'jabatan':forms.Select(attrs={
                'class':'form-control'
            })
        }


class PerusahaanForm(forms.ModelForm):
    class Meta:
        model = Perusahaan
        exclude = ('username','pembina','npp',)

        widgets = {
            'nama_pemilik':forms.TextInput(attrs={
                'class':'form-control'
            }),
            'nik':forms.TextInput(attrs={
                'class':'form-control'
            }),
            'jabatan':forms.TextInput(attrs={
                'class':'form-control'
            }),
            'email':forms.EmailInput(attrs={
                'class':'form-control',
            }),
            'no_hp':forms.TextInput(attrs={
                'class':'form-control', 'maxlength':'13'
            }),
            'nama_pic':forms.TextInput(attrs={
                'class':'form-control'
            }),
            'alamat':forms.TextInput(attrs={
                'class':'form-control'
            }),
            'kode_pos':forms.TextInput(attrs={
                'class':'form-control', 'maxlength':'5'
            }),
            'npwp_prsh':forms.TextInput(attrs={
                'class':'form-control', 'maxlength':'15'
            }),
            'desa_kel':forms.TextInput(attrs={
                'class':'form-control','maxlength':'100'
            }),
            'kecamatan':forms.TextInput(attrs={
                'class':'form-control','maxlength':'100'
            }),
            'kota_kab':forms.TextInput(attrs={
                'class':'form-control', 'maxlength':'100'
            })
        }

kepesertaan/templates/kepesertaan/create_informasi.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{% endblock title %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'kepesertaan/css/informasi.css' %}">
{% endblock stylesheets %}

{% block content %}
<div class="row">
    <div class="col-md-12 px-5">
        <div class="card mb-3">
            <div class="card-header">
                <div class="nav-tabs-navigation">
                    <div class="nav-tabs-wrapper" style="font-size: small; font-weight: bold;">
                        <ul class="nav nav-tabs" data-tabs="tabs">
                            <li class="nav-item mr-2">
                                <a href="#list_informasi" class="nav-link color-nav-link active" data-toggle="tab">
                                    <i class="fas fa-info-circle"></i>  Informasi
                                </a>
                            </li>
                            {% if kepala %}
                            <li class="nav-item mr-2">
                                <a href="#buat_informasi" class="nav-link color-nav-link" data-toggle="tab">
                                    <i class="far fa-clipboard"></i>  Buat Informasi
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div id="alert"></div>
                <div class="tab-content">
                    <div class="tab-pane active" id="list_informasi">
                        {% include 'kepesertaan/informasi_section.html' %}
                    </div>
                    {% if kepala %}
                    <div class="tab-pane" id="buat_informasi">
                        <form method="post" ecntype="multipart/form-data" id="id_kirim_informasi">
                            {% csrf_token %}
                            <div class="row justify-content-center">
                                <div class="col">
                                    <div class="form-group">
                                        <label for="id_judul">Judul</label>
                                        <input type="text" class="form-control" id="id_judul" maxlength="100" name="judul">
                                    </div>
                                    <div class="form-group">
                                        <label for="id_isi">Isi</label>
                                        <textarea name="isi" id="id_isi" rows="5%" cols="100%" class="form-control"></textarea>
                                    </div>
                                    <div class="form-group">
                                        <label for="id_attachment">Attachment</label>
                                        <input type="file" name="attachment" id="id_attachment" class="form-control-file">
                                    </div>
                                    
                                    <div class="form-group">
                                        <label for="id_kirim_ke_npp">Kirim Ke</label>
                                        <select class="form-control" id="id_kirim_ke_npp" name="kirim_ke_npp">
                                            <option value="0">.....</option>
                                            <option value="1">Semua</option>
                                            <option value="2">Pilih NPP</option>
                                        </select>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12" id="id_check_npp">
                                            {% include 'kepesertaan/table_info.html' %}
                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                            <button type="button" class="btn btn-sm btn-primary float-right mt-3" id="id_submit_info" disabled>Submit</button>
                        </form>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

{% block javascripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js" integrity="sha512-37T7leoNS06R80c8Ulq7cdCDU5MNQBwlYoy1TX/WUsLFC2eYNqtKlV0QjH7r8JpG/S0GUMZwebnVFLPd6SU5yg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{% static 'kepesertaan/js/informasi.js' %}"></script>
{% endblock  %}

kepesertaan/templates/kepesertaan/edit_pers.html
{% extends 'base.html' %}

{% block title %}Edit NPP {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="container-fluid">
    <div class="col">
        <div class="card">
            <div class="card-header text-center">
                Edit NPP
            </div>
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="row">

                        <div class="col-6">
                            <div class="form-group">
                                <label for="id_nama_pic">Nama PIC</label>
                                {{form.nama_pic}}
                            </div>
                            <div class="form-group">
                                <label for="id_nik">NIK</label>
                                {{form.nik}}
                            </div>
                            <div class="form-group">
                                <label for="id_jabatan">Jabatan</label>
                                {{form.jabatan}}
                            </div>
                            <div class="form-group">
                                <label for="id_no_hp">No Handphone</label>
                                {{form.no_hp}}
                            </div>
                            <div class="form-group">
                                <label for="id_email">Email</label>
                                {{form.email}}
                            </div>
                            <div class="form-group">
                                <label for="id_npwp_prsh">NPWP Perusahaan</label>
                                {{form.npwp_prsh}}
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="id_nama_pemilik">Nama Pemilik Perusahaan</label>
                                {{form.nama_pemilik}}
                            </div>
                            <div class="form-group">
                                <label for="id_alamat">Alamat Perusahaan</label>
                                {{form.alamat}}
                            </div>
                            <div class="form-group">
                                <label for="id_kode_pos">Kode Pos</label>
                                {{form.kode_pos}}
                            </div>
                            <div class="form-group">
                                <label for="id_desa_kel">Desa/Kelurahan</label>
                                {{form.desa_kel}}
                            </div>
                            <div class="form-group">
                                <label for="id_kecamatan">Kecamatan</label>
                                {{form.kecamatan}}
                            </div>
                            <div class="form-group">
                                <label for="id_kota_kab">Kota/Kabupaten</label>
                                {{form.kota_kab}}
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary float-right">UPDATE</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascripts %}{% endblock javascripts %}

kepesertaan/templates/kepesertaan/edit_profile.html
{% extends 'base.html' %}

{% block title %}
Edit Profile | {{request.user}}
{% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="container-fluid d-flex justify-content-center">
    <div class="col-5">
        <div class="card">
            <div class="card-header text-center">
                Edit Profile - {{request.user}}
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_nama">Nama</label>
                        <span style="color:red;">*</span>
                        {{form.nama}}
                    </div>
                    <div class="form-group">
                        <label for="id_email">Email</label>
                        <span style="color:red;">*</span>
                        {{form.email}}
                    </div>
                    <div class="form-group">
                        <label for="id_no_hp">No. Handphone</label>
                        <span style="color:red;">*</span>
                        {{form.no_hp}}
                    </div>
                    <div class="form-group">
                        <label for="id_jabatan">Jabatan</label>
                        <span style="color:red;">*</span>
                        {{form.jabatan}}
                    </div>
                    <button type="submit" class="btn btn-sm btn-primary float-right">SIMPAN</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascripts %}{% endblock javascripts %}

kepesertaan/templates/kepesertaan/informasi.html
{% extends 'base.html' %}
{% block title %}Informasi{% endblock title %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card mb-3">
            <div class="card-header">
                <div class="nav-tabs-navigation">
                    <div class="nav-tabs-wrapper" style="font-size:small;font-weight:bold">
                        <ul class="nav nav-tabs" data-tabs="tabs">
                            <li class="nav-item mr-2">
                                <a href="#show_data" class="nav-link active" data-toggle="tab">
                                    <i class="fas fa-fw fa-file-alt"> </i>
                                     List Informasi
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="tab-content">
                    <div class="tab-pane active" id="show_data">
                        <div class="row justify-content-center">
                            <div class="col-md-12">
                                <div class="card mb-2">
                                    <div class="card-body">
                                        <div class="row">
                                            {% if info %}
                                                {% for data in info %}
                                                <div class="col-sm-12 grid-margin mb-3">
                                                    <h4 class="mb-2 font-weight-bold text-primary">
                                                      {{data.judul}}  
                                                    </h4>
                                                    <div class="font-italic mb-2 text-muted" style="font-size:0.70rem;">
                                                        <span class="mr-2"><small>{{data.created}}</small></span>
                                                    </div>
                                                    <p class="mb-0 text-truncate" style="font-size:0.85rem;width:82%;height:50px;">
                                                        {{data.isi}}
                                                        <span><a href="{{data.pk}}" class="nav-link">read more</a></span>
                                                    </p>
                                                    <p class="mb-0 mt-2" style="font-size:0.80rem">
                                                        {% if data.attachment %}
                                                        <a href="{{data.attachment.url}}" class="btn btn-sm btn-primary">{{data.filename}}</a>
                                                        {% else %}
                                                            No Attachment!
                                                        {% endif %}
                                                        <a href="/" class="btn btn-sm btn-success float-right" onclick="return confirm('Hapus data ini ?')">Hapus</a>
                                                    </p>
                                                    <hr clas="col-12 justify-content-end">
                                                </div>
                                                {% endfor %}
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

kepesertaan/templates/kepesertaan/pindah_binaan.html
{% extends 'base.html' %}

{% block title %}Distribusi Perusahaan Binaan{% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header bg-primary">
                    <div class="card-title text-center text-white fw-bold" style="font-weight:600;">
                        PINDAH BINAAN
                    </div>
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <table class="table table-bordered text-center" id="id_npp_table">
                                <thead>
                                    <th>Pilih</th>
                                    <th>NPP</th>
                                    <th>NAMA PERUSAHAAN</th>
                                </thead>
                                <tbody>
                                    {% for data in datas %}
                                    <tr>
                                        <td><input type="checkbox" class="form-check-input" value="{{data.npp}}" id="cb_{{data.pk}}"></td>
                                        <td>{{data.npp}}</td>
                                        <td>{{data.nama_perusahaan}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="form-group row">
                            <div class="col-2">
                                <label for="id_pembina">USER PEMBINA</label>
                                <input type="text" id="id_pembina" class="form-control" required onkeyup="this.value = this.value.toUpperCase()" maxlength="8">
                            </div>
                            <div class="col-4">
                                <label for="id_hasil_pembina">NAMA</label>
                                <input type="text" id="id_hasil_pembina" class="form-control" disabled>
                            </div>
                        </div>
                        <div class="form-group">
                            <button id="btn-simpan" class="btn btn-primary" onclick="getValues()" type="button">SIMPAN</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block javascripts %}
<script>
    var subQuery =`
query getUser($user:String!){
    allPembinaBidang(user:$user){
        id
        username{
        username
        }
        nama
    }
}
`

    $(document).ready( function () {
        $('#id_npp_table').DataTable();

        $("#id_pembina").on("focusout", function(){
            $.ajax({
                method:"POST",
                url:"{% url 'graphql' %}",
                contentType:"application/json",
                data:JSON.stringify({
                    query:subQuery,
                    variables:{
                        user:$(this).val()
                    }
                }),
                dataType:"json",
                success:function(res){
                    var hasil = res.data.allPembinaBidang[0]
                    
                    if(hasil === undefined){
                        Swal.fire({
                            text:"KODE PEMBINA TIDAK DITEMUKAN / KODE PEMBINA TIDAK BOLEH SAMA",
                            icon:'error',
                            confirmButtonText: 'OK'
                        })
                        $("#id_hasil_pembina").val("")                    
                    }
                    $("#id_hasil_pembina").val(hasil["username"]["username"]+' - '+hasil.nama)
                    $("#id_hasil_pembina").attr("data-id",hasil.id)
                    
                },
                error:function(err){
                    console.log(err)
                }
            })
        })
    } );

    function getValues(){
        var selected = new Array();
        var chckbox = document.getElementById("id_npp_table")
        var selchk = chckbox.getElementsByTagName("input")



        for(var i=0;i<selchk.length;i++){
            if(selchk[i].checked){
                selected.push(selchk[i].value);
            }
        }

        if((selected.length>0) && ($("#id_pembina").val() !== ''))
        {   
            if(confirm("Apakah anda yakin ?") == true){
                
                selected.forEach(item => {
                   var form = new FormData()
                   form.append("pembina",$("#id_hasil_pembina").attr("data-id"))
                   form.append("npp", item)
                   form.append("csrfmiddlewaretoken", $("input[name='csrfmiddlewaretoken']").val())
                    $.ajax({
                        type:"POST",
                        url:"{% url 'update-binaan' %}",
                        contentType:false,
                        processData:false,
                        data:form,
                        success:function(e){
                            location.reload();
                        },
                        error:function(err){
                            console.log(err)
                        }
                    })
                })
            } 
        }else{
            Swal.fire({
                text: 'Data tidak boleh kosong!',
                icon: 'error',
                confirmButtonText: 'OK'
            })
           
        }
    }
</script>

{% endblock javascripts %}

kepesertaan/templates/kepesertaan/table_info.html
<div class="scroll">
    <table class="table table-borderless" id="id_tbl_check_npp">
        <tbody>
            {% for data in datas %}
            <tr>
              <td>
                <input id="id_cek_npp" type="checkbox" name="cek_npp" value="{{data.username.pk}}">
              </td>
              <td>{{data.npp}}</td>
              <td>{{data.nama_perusahaan}}</td>  
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>