admin_page/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='admindex'),
    path('create-user/', views.page_user, name='page-user'),
    path('create-user/ajax/', views.create_user_internal, name='create-user-internal')
]

chat/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('testing/', views.index, name='index'),
    path('<str:room_name>/', views.chatbox, name='chat'),
    path('create/thread/', views.create_chat, name='create-thread'),
    path('save/chat/', views.save_chat, name='save-chat'),
    path('load/chat/', views.load_chat),
    path('read/done/', views.is_read_chat),
    path('load/read/', views.load_read)
]

core/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

# from core.settings import MEDIA_ROOT

from .views import delete_user, login_view, logout_view, edit_password

from graphene_django.views import GraphQLView

urlpatterns = [
    path('', include('kepesertaan.urls')),
    path('chat/', include('chat.urls')),
    path('mychats/', include('mychats.urls')),
    path('kunjungan/', include('kunjungan.urls')),
    path('admin-page/', include('admin_page.urls')),
    path("graphql", csrf_exempt(GraphQLView.as_view(graphiql=True)), name="graphql"),
    path('accounts/login/', login_view, name='login'),
    path('accounts/logout/', logout_view, name='logout'),
    path('ganti/password/<int:pk>', edit_password, name='edit-password'),
    path('accounts/reset_password/', auth_views.PasswordResetView.as_view(template_name="registration/reset_password.html"), name="reset_password"),
    path('accounts/reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name="registration/reset_password_confirmation.html"), name="password_reset_done"),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('accounts/reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('hapus/user/<int:pk>', delete_user, name='hapus-user'),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin_page/models.py
from django.db import models

# Create your models here.

kepesertaan/models.py
import os
from django.conf import settings
from django.db import models
# from django.contrib.auth import get_user_model
# from django.core.files.storage import FileSystemStorage
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
# from django.db.models.signals import post_save
# from django.dispatch import receiver

# User = get_user_model()

info_save = '/home/reah4319/jrealitas/public/'

NIK_VALIDATOR = RegexValidator("^\d{16}$","Format NIK Tidak Sesuai")
HP_VALIDATOR = RegexValidator("^(08+[1-9])([0-9]{7,10})$", "Format NO HP TIDAK SESUA!!!")

class Kantor(models.Model):
    kode_kantor = models.CharField(max_length=3)
    nama_kantor = models.CharField(max_length=100)
    alamat = models.CharField(max_length=250)

    def __str__(self):
        return f'{self.kode_kantor} - {self.nama_kantor}'

class Bidang(models.Model):
    kode_bidang = models.CharField(max_length=3)
    nama_bidang = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.kode_bidang} - {self.nama_bidang}'

class Jabatan(models.Model):
    bidang = models.ForeignKey(Bidang, on_delete=models.CASCADE)
    kode_jabatan = models.CharField(max_length=3)
    nama_jabatan = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.kode_jabatan} - {self.nama_jabatan}'

# @receiver(post_save, sender=User)
# def post_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(username=instance)
    
class Profile(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    nama = models.CharField(max_length=100)
    no_hp = models.CharField(max_length=13, validators=[HP_VALIDATOR])
    jabatan = models.ForeignKey(Jabatan, on_delete=models.CASCADE)
    kode_kantor = models.ForeignKey(Kantor, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.username} - {self.nama}'



class Perusahaan(models.Model):
    nama_pemilik = models.CharField(max_length=100, blank=True, null=True)
    nik = models.CharField(max_length=16, validators=[NIK_VALIDATOR], blank=True, null=True)
    jabatan = models.CharField(max_length=50, default="HRD")
    email = models.EmailField(max_length=100, blank=True, null=True)
    no_hp = models.CharField(max_length=13, validators=[HP_VALIDATOR], blank=True, null=True)
    npp = models.CharField(max_length=8)
    nama_perusahaan = models.CharField(max_length=200)
    nama_pic = models.CharField(max_length=100)
    alamat = models.CharField(max_length=250, blank=True, null=True)
    kode_pos = models.CharField(max_length=5, blank=True, null=True)
    npwp_prsh = models.CharField(max_length=15, blank=True, null=True)
    desa_kel = models.CharField(max_length=100, blank=True, null=True)
    kecamatan = models.CharField(max_length=100, blank=True, null=True)
    kota_kab = models.CharField(max_length=100, blank=True, null=True)
    status = models.BooleanField(default=False)
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    pembina = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.npp} - {self.nama_perusahaan}'

    def total_npp(*args, **kwargs):
        
        npp = Perusahaan.objects.select_related('pembina').filter(pembina__username__username=kwargs['kwargs'])
        return npp.count()


class Tenaga_kerja(models.Model):
    npp = models.ForeignKey(Perusahaan, on_delete=models.CASCADE)
    nama = models.CharField(max_length=100)
    no_kartu = models.CharField(max_length=11)
    no_hp = models.CharField(max_length=13, validators=[HP_VALIDATOR])
    email = models.EmailField(max_length=100, blank=True, null=True)
    tgl_lahir = models.DateField()
    tgl_keps = models.DateField()
    tgl_na = models.DateField(blank=True, null=True)

    def __str__(self):
        return f'{self.no_kartu} - {self.nama}'

class Informasi(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    judul = models.CharField(max_length=200)
    attachment = models.FileField(upload_to='informasi/attachment', blank=True, null=True)
    isi = models.TextField()
    created_by = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.created_by.username.username} - {self.judul}'

admin_page/forms.py
from django import forms

from kepesertaan.models import Profile, Kantor, Bidang, Jabatan

class PembinaForm(forms.ModelForm):
    def __init__(self, bidang_id, *args, **kwargs):
        super(PembinaForm, self).__init__(*args, **kwargs)
        self.fields['jabatan'].queryset = self.fields['jabatan'].queryset.filter(bidang__kode_bidang=bidang_id)

    class Meta:
        model = Profile
        fields = '__all__'

        widgets = {
            'username':forms.TextInput(attrs={
                'class':'form-control', 'disabled':'disabled','onkeyup':'this.value = this.value.toUpperCase()'
            }),
            'nama':forms.TextInput(attrs={
                'class':'form-control','onkeyup':'this.value = this.value.toUpperCase()'
            }),
            'email':forms.EmailInput(attrs={
                'class':'form-control','onkeyup':'this.value = this.value.toUpperCase()'
            }),
            'no_hp':forms.TextInput(attrs={
                'class':'form-control'
            }),
            'jabatan':forms.Select(attrs={
                'class':'form-control',
            }),
            'kode_kantor':forms.Select(attrs={
                'class':'form-control'
            })
        }

# class KantorForm(forms.ModelForm):
#     class Meta:
#         model = Kantor
#         fields = '__all__'

#         widgets = {
#             'kode_kantor':forms.TextInput(attrs={
#                 'class':'form-control','maxlength':'3'
#             }),
#             'nama_kantor':forms.TextInput(attrs={
#                 'class':'form-control','maxlength':'100'
#             }),
#             'alamat':forms.Textarea(attrs={
#                 'class':'form-control'
#             })
#         }

class BidangForm(forms.ModelForm):
    class Meta:
        model = Bidang
        fields = '__all__'

        widgets = {
            'kode_bidang':forms.TextInput(attrs={
                'class':'form-control','maxlength':'3'
            }),
            'nama_bidang':forms.TextInput(attrs={
                'class':'form-control','maxlength':'50'
            })
        }

class JabatanForm(forms.ModelForm):
    class Meta:
        model = Jabatan
        fields = '__all__'

        widgets = {
            'kode_jabatan':forms.TextInput(attrs={
                'class':'form-control','maxlength':'3'
            }),
            'nama_jabatan':forms.TextInput(attrs={
                'class':'form-control','maxlength':'100'
            }),
            'bidang':forms.Select(attrs={
                'class':'form-control'
            })
        }

admin_page/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.hashers import make_password
from django.http import JsonResponse
from django.db.models import Q, Count

from kepesertaan.models import Kantor, Bidang, Jabatan, Perusahaan, Profile, Tenaga_kerja
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required

from core.decorators import adminuser_only

from .forms import BidangForm, JabatanForm, PembinaForm



@login_required
@adminuser_only
def index(request):
    # data = []
    profile = Profile.objects.select_related('username','jabatan').all()
    per_profile = profile.filter(Q(jabatan__kode_jabatan=7) | Q(jabatan__kode_jabatan=8))

    data = per_profile.annotate(num_npp=Count('perusahaan', distinct=True)).annotate(total_tk=Count('perusahaan__tenaga_kerja'))

    # for d in data:
    #     print(d.username.username," : ", d.num_npp, " : ", d.total_tk)
    context = {
        'datas':data
    }
    return render(request, 'admin_page/index.html', context)

@login_required
@adminuser_only
def page_user(request):
    datas = Profile.objects.all()
    form = PembinaForm(request.POST)
    return render(request, 'admin_page/buat_profile.html',{'form':form, 'datas':datas})

@login_required
def create_bidang(request):
    form = BidangForm()
    if request.method == 'POST':
        form = BidangForm(request.POST or None)
        if form.is_valid():
            form.save()
            return redirect('admindex')
    return render(request, 'admin_page/buat_bidang.html', {'form':form})

@login_required
@adminuser_only
def create_user_internal(request):
    kd_kantor = request.POST.get('kd_kantor')
    nama = request.POST.get('nama')
    jabatan = request.POST.get('jabatan')
    email = str(request.POST.get('email')).lower()
    no_hp = request.POST.get('no_hp')
    username = request.POST.get('username')
    password1 = request.POST.get('password1')
    password2 = request.POST.get('password2')


    cek_user = User.objects.filter(username=username)
    if cek_user.exists():
        return JsonResponse({'error':'User sudah pernah terdaftar!'})
    else:
        if password1 == password2 :
            group = Group.objects.get(name='pembina')
            password = make_password(password1, hasher='default')
            user = User.objects.create(username=username, password=password, email=email)
            user.groups.add(group.id)
            user.save()

            Profile.objects.create(username_id=user.pk,nama=nama, jabatan_id=jabatan,
                kode_kantor_id=kd_kantor, no_hp=no_hp)

            return JsonResponse({'success':'done'})
        else:
            return JsonResponse({'data_error':'Password tidak sama!'})
            
            

admin_page/templates/admin_page/buat_bidang.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Create Bidang
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-md-12 px-5">
        <div class="card mb-3">
            <div class="card-header bg-primary">
                Create Bidang
            </div>
            <div class="card-body">
                
            </div>
        </div>
    </div>
</div>
{% endblock content %}

admin_page/templates/admin_page/buat_profile.html
{% extends 'base2.html' %}

{% block title %}Create User Internal{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-md-12 px-5 mt-5">
        <div class="card mb-3">
            <div class="card-header">
                <div class="nav-tabs-navigation">
                    <div class="nav-tabs-wrapper" style="font-size: small; font-weight: bold;">
                        <ul class="nav nav-tabs" data-tabs="tabs">
                            <li class="nav-item mr-2">
                                <a href="#id_list_pegawai" class="color-nav-link nav-link active" data-toggle="tab">
                                    <i class="fas fa-fw fa-users"> </i> Karyawan
                                </a>
                            </li>
                            <li class="nav-item mr-2">
                                <a href="#register_karyawan" class="color-nav-link nav-link" data-toggle="tab">
                                    <i class="fas fa-fw fa-user-plus"> </i>Registrasi Karyawan
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                
            </div>
            <div class="card-body">
                <div class="tab-content">
                    <div style="font-size:14px;" class="tab-pane active" id="id_list_pegawai">
                        <div class="table-responsive mt-3">
                            <table id="example2" class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>NO</th>
                                        <th>USER</th>
                                        <th>NAMA LENGKAP</th>
                                        <th>JABATAN</th>
                                        <th>EMAIL</th>
                                        <th>NO HANDPHONE</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for data in datas %}
                                    <tr>
                                        <td>{{forloop.counter}}</td>
                                        <td>{{data.username.username}}</td>
                                        <td>{{data.nama}}</td>
                                        <td>{{data.jabatan.kode_jabatan}} - {{data.jabatan.nama_jabatan}}</td>
                                        <td>{{data.username.email}}</td>
                                        <td>{{data.no_hp}}</td>
                                        <td>
                                            <a href="#" class="badge badge-primary" data-pk="{{data.username.pk}}" id="id_ganti_pass{{data.username.pk}}" data-user="{{data.username.username}}">Ganti Password</a>
                                        </td>
                                    </tr>
                                    <!-- Modal Change Password -->
                                    
                                    <!-- Modal Pindah Binaan -->
                                    
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="tab-pane" id="register_karyawan">
                        <form id="form_register_pembina" method="POST">
                            {% csrf_token %}
                            <div class="row justify-content-center">
                                <div class="col md-5">
                                    <div class="form-group">
                                        <label for="nama">Nama Lengkap</label>
                                        <span style="color:red;">*</span>
                                        {{form.nama}}
                                    </div>
                                    <div class="form-group">
                                        <label for="makeselect">Jabatan</label>
                                        <span style="color:red;">*</span>
                                        {{form.jabatan}}
                                    </div>
                                    <div class="form-group">
                                        <label for="no_hp">No Handphone</label>
                                        <span style="color:red;">*</span>
                                        {{form.no_hp}}
                                    </div>
                                    <div class="form-group">
                                        <label for="kd_user">Kode User</label>
                                        <span style="color:red;">*</span>
                                        <input type="text" class="form-control clear" id="kd_user" name="kd_user" onkeyup="this.value = this.value.toUpperCase()" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="kd_user">Kode Kantor</label>
                                        <span style="color:red;">*</span>
                                        {{form.kode_kantor}}
                                    </div>
                                </div>
                                <div class="col md-5">
                                    <div class="form-group">
                                        <label for="email">Email</label>
                                        <span style="color:red;">*</span>
                                        <input type="text" class="form-control clear" id="email_pembina" name="email" onkeyup="this.value = this.value.toUpperCase()" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="pembaina_username">Username</label>
                                        <span style="color:red;">*</span>
                                        {{form.username}}
                                    </div>
                                    <div class="form-group">
                                        <label for="pembina_password1">Password</label>
                                        <span style="color:red;">*</span>
                                        <input type="password" name="id_password_1" id="id_password_1" class="form-control clear" minlength="8" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="pembina_password2">Ulangi Password</label>
                                        <span style="color:red;">*</span>
                                        <input type="password" name="id_password_2" id="id_password_2" class="form-control clear" minlength="8" required>
                                    </div>
                                    
                                   <div class="form-group">
                                        <button type="button" class="btn btn-success float-right mt-4" id="id_Daftar_btn">Daftar</button>
                                   </div>
                                </div>
                            </div>
                        </form>
                    <div>
                </div>
                
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascripts %}
<script>
var superQuery = `query{
    allJabatan{
        id
        kodeJabatan
        namaJabatan
    }
    }`

    function DaftarPembina() {
        var data = new FormData()
        data.append("nama", $("#id_nama").val())
        data.append("jabatan", $('select#id_jabatan option').filter(':selected').val())
        data.append("kd_kantor", $('select#id_kode_kantor option').filter(':selected').val())
        data.append("kepala_id", $("#id_jabatan_pembina").val())
        data.append("email",$("#email_pembina").val())
        data.append("no_hp",$("#id_no_hp").val())
        data.append("username", $("#id_username").val())
        data.append("password1", $("#id_password_1").val())
        data.append("password2", $("#id_password_1").val())
        data.append("csrfmiddlewaretoken", $("input[name='csrfmiddlewaretoken']").val())
        
        $.ajax({
            method:"POST",
            url:"{% url 'create-user-internal' %}",
            contentType:false,
            processData:false,
            data:data,
            success:function(res){
                
                
                if(res['error']){
                    Swal.fire({
                        icon: 'error',
                        title: 'Error!',
                        text: 'Username sudah terdaftar sebelumnya!',
                        
                      })
                }
                if(res['success']){
                    Swal.fire({
                        icon: 'success',
                        title: 'Success',
                        text: 'Data Berhasil disimpan',
                        preConfirm:function(){
                            window.location.reload()
                        }
                      })
                }
                if(res['data_error']){
                    Swal.fire({
                        icon: 'error',
                        title: 'Error!',
                        text: 'Password Tidak Sama',
                      })
                }
                
            },
            error:function(err){
                console.log(err)
            }
        })
        
    }

    function resetPassword(pk, pass1, pass2){

        var data = new FormData()
        data.append("id_pembina",$("#id_ganti_password_pembina").val())
        data.append("password1", pass1)
        data.append("password2", pass2)
        data.append("csrfmiddlewaretoken", $("input[name='csrfmiddlewaretoken']").val())
        $.ajax({
            method:"POST",
            url:`/ganti/password/${pk}`,
            contentType:false,
            processData:false,
            data:data,
            success:function(data){
                console.log(data)
                
            },
            error:function(err){
                console.log(err)
            }
        })
    }

    $(document).ready(function(){
        $('#example').DataTable();

        //reset password

        var rowCount = $("#example2 tr").length;
        for(var i=1;i<rowCount;i++){
            var tr = $(`#example2 tr:nth-child(${i}) td:nth-child(7) a`)
            console.log($("#example tr:nth-child(1) td"))
            var pk = tr.attr("data-pk")
            
            $(`#id_ganti_pass${pk}`).click((e) => {

                var dataUser = e.target.dataset.user
                const swalWithBootstrapButtons = Swal.mixin({
                    customClass: {
                    confirmButton: 'btn btn-success',
                    },
                    buttonsStyling: false
                })
                
                swalWithBootstrapButtons.fire({
                    title: `Ubah Sandi</br>${dataUser}`,
                    html:
                    '<input id="password_1" class="swal2-input" placeholder="Password" type="password">' +
                    '<input id="password_2" class="swal2-input" placeholder="Password Konfirmasi" type="password">',
                    
                    showCancelButton: false,
                    confirmButtonText: 'SUBMIT',
                }).then((result) => {
                    if (result.isConfirmed) {
                        var pass1 = $("#password_1").val()
                        var pass2 = $("#password_2").val()

                        resetPassword(e.target.dataset.pk, pass1, pass2)
                        swalWithBootstrapButtons.fire(
                            'Berhasil!',
                            `Sandi ${dataUser} berhasil diganti.`,
                            'success'
                        )
                    } 
                })
                
            })
        }

        //end

        $("#kd_user").on("focusout", function() {
            var kd_user = $(this).val()
            $("#id_username").val(kd_user)
        })

        $.ajax({
            method:"POST",
            url:"{% url 'graphql' %}",
            contentType:"application/json",
            data:JSON.stringify({
                query:superQuery,
            }),
            dataType:"json",
            success:function(data){
                var datas = data['data']['allJabatan']
                
                $.each(datas, function(i,j){
    
                    $("#id_jabatan").append($('<option>', {
                        
                        value:j['id'],
                        text:j['id']+" - "+j['namaJabatan'],       
                    }));
                })
              
            },
            error:function(err){
                console.log(err)
            }
        })

        $("#id_Daftar_btn").click(function(){
            DaftarPembina()
        })
    })
</script>

{% endblock javascripts %}

admin_page/templates/admin_page/index.html
{% extends 'base.html' %}
{% block title %}Admin Page{% endblock title %}

{% block content %}
<div class="row px-3">
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase">
                            Total Perusahaan</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{total_npp}}</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-industry fa-2x text-primary mt-2"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            Tenaga Kerja</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{total_tk}}</div>
                    </div>
                    <div class="col-auto">
                        <i class="fa fa-briefcase fa-2x text-success mt-2">
                        </i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row px-3">
    <div class="col-xl-8">
        <div class="card">
            <div class="card-body">
                <h4 class="box-title">Daftar Pembina </h4>
            </div>
            <div class="card-body--">
                <div class="table">
                    <table class="table text-center" id="id_table_total">
                        <thead>
                            <tr class="bg-light">
                                <th class="serial">#</th>
                                <th>User</th>
                                <th>Nama</th>
                                <th>Total NPP</th>
                                <th>Total Tenaga Kerja</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for data in datas %}
                            <tr>
                                <td class="serial">{{forloop.counter}}</td>
                                <td>{{data.username.username}}</td>
                                <td>{{data.nama}}</td>
                                <td>{{data.num_npp}}</td>
                                <td>{{data.total_tk}}</td>
                            </tr>
                            {% endfor %}
                            
                        </tbody>
                    </table>
                </div> <!-- /.table-stats -->
            </div>
        </div> <!-- /.card -->
    </div>  <!-- /.col-lg-8 -->

    <div class="col-xl-4">
        <div class="row">
            <div class="col-lg-6 col-xl-12">
                
            </div>

           
        </div>
    </div> <!-- /.col-md-4 -->
</div>
{% endblock content %}

{% block javascripts %}
$(document).ready(function() {
    $('#id_table_total').DataTable();
    
})
{% endblock javascripts %}